apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: "<RABBITMQ_USERNAME>"
  password: "<RABBITMQ_PASSWORD>"
  uri: "amqp://<RABBITMQ_USERNAME>:<RABBITMQ_PASSWORD>@rabbitmq:5672/"
---
apiVersion: v1
kind: Secret
metadata:
  name: external-apis
type: Opaque
stringData:
  osrm: "https://osrm.selfmadeengineer.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
type: Opaque
stringData:
   stripe-secret-key: "<STRIPE_SECRET_KEY>"
   stripe-webhook-key: "<STRIPE_WEBHOOK_KEY>"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
stringData:
  uri: "<MONGODB_URI>"
